// <auto-generated />
using HRAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRAPI.Migrations
{
    [DbContext(typeof(HRSysContext))]
    partial class HRSysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRAPI.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("HRAPI.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ivan.petrov@gmail.com",
                            FirstName = "Ivan",
                            JobTitle = "Engineering Manager",
                            LastName = "Petrov",
                            Salary = 9200m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "maria.georgieva@abv.bg",
                            FirstName = "Maria",
                            JobTitle = "Software Engineer",
                            LastName = "Georgieva",
                            Salary = 6700m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Email = "georgi.ivanov@gmail.com",
                            FirstName = "Georgi",
                            JobTitle = "QA Engineer",
                            LastName = "Ivanov",
                            Salary = 3900m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "desislava.nikolova@abv.bg",
                            FirstName = "Desislava",
                            JobTitle = "DevOps Engineer",
                            LastName = "Nikolova",
                            Salary = 6100m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Email = "petar.dimitrov@gmail.com",
                            FirstName = "Petar",
                            JobTitle = "Backend Developer",
                            LastName = "Dimitrov",
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Email = "anton.simeonov@abv.bg",
                            FirstName = "Anton",
                            JobTitle = "Frontend Developer",
                            LastName = "Simeonov",
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Email = "radoslav.iliev@gmail.com",
                            FirstName = "Radoslav",
                            JobTitle = "Software Engineer",
                            LastName = "Iliev",
                            Salary = 6100m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Email = "yulian.stoyanov@abv.bg",
                            FirstName = "Yulian",
                            JobTitle = "QA Engineer",
                            LastName = "Stoyanov",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 1,
                            Email = "valentina.hristova@gmail.com",
                            FirstName = "Valentina",
                            JobTitle = "DevOps Engineer",
                            LastName = "Hristova",
                            Salary = 6200m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            Email = "milena.yordanova@abv.bg",
                            FirstName = "Milena",
                            JobTitle = "Programmer",
                            LastName = "Yordanova",
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Email = "nikola.mihailov@gmail.com",
                            FirstName = "Nikola",
                            JobTitle = "Support Engineer",
                            LastName = "Mihailov",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 1,
                            Email = "liliya.koleva@abv.bg",
                            FirstName = "Liliya",
                            JobTitle = "QA Specialist",
                            LastName = "Koleva",
                            Salary = 2800m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 1,
                            Email = "todor.vasilev@gmail.com",
                            FirstName = "Todor",
                            JobTitle = "System Administrator",
                            LastName = "Vasilev",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 1,
                            Email = "stanislav.petkov@abv.bg",
                            FirstName = "Stanislav",
                            JobTitle = "Frontend Developer",
                            LastName = "Petkov",
                            Salary = 3300m
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 1,
                            Email = "martin.grozdanov@gmail.com",
                            FirstName = "Martin",
                            JobTitle = "Software Engineer",
                            LastName = "Grozdanov",
                            Salary = 6700m
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            Email = "ivaylo.marinov@abv.bg",
                            FirstName = "Ivaylo",
                            JobTitle = "DevOps Engineer",
                            LastName = "Marinov",
                            Salary = 5700m
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            Email = "borislav.pavlov@gmail.com",
                            FirstName = "Borislav",
                            JobTitle = "Backend Developer",
                            LastName = "Pavlov",
                            Salary = 4100m
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            Email = "vasil.stankov@abv.bg",
                            FirstName = "Vasil",
                            JobTitle = "Software Engineer",
                            LastName = "Stankov",
                            Salary = 4600m
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 1,
                            Email = "polina.dobreva@gmail.com",
                            FirstName = "Polina",
                            JobTitle = "QA Tester",
                            LastName = "Dobreva",
                            Salary = 2700m
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 1,
                            Email = "kaloyan.angelov@abv.bg",
                            FirstName = "Kaloyan",
                            JobTitle = "Frontend Developer",
                            LastName = "Angelov",
                            Salary = 3100m
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 1,
                            Email = "kristina.filipova@gmail.com",
                            FirstName = "Kristina",
                            JobTitle = "QA Specialist",
                            LastName = "Filipova",
                            Salary = 2900m
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 1,
                            Email = "miroslav.borisov@abv.bg",
                            FirstName = "Miroslav",
                            JobTitle = "DevOps Engineer",
                            LastName = "Borisov",
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 1,
                            Email = "teodora.mitkova@gmail.com",
                            FirstName = "Teodora",
                            JobTitle = "Support Engineer",
                            LastName = "Mitkova",
                            Salary = 3100m
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 1,
                            Email = "zhivko.yordanov@abv.bg",
                            FirstName = "Zhivko",
                            JobTitle = "QA Engineer",
                            LastName = "Yordanov",
                            Salary = 3900m
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 1,
                            Email = "radostin.tsanev@gmail.com",
                            FirstName = "Radostin",
                            JobTitle = "System Administrator",
                            LastName = "Tsanev",
                            Salary = 4200m
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 2,
                            Email = "kalina.petkova@gmail.com",
                            FirstName = "Kalina",
                            JobTitle = "Finance Manager",
                            LastName = "Petkova",
                            Salary = 8300m
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 2,
                            Email = "borislav.todorov@abv.bg",
                            FirstName = "Borislav",
                            JobTitle = "Accountant",
                            LastName = "Todorov",
                            Salary = 4200m
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 2,
                            Email = "ralica.ganeva@gmail.com",
                            FirstName = "Ralica",
                            JobTitle = "Financial Analyst",
                            LastName = "Ganeva",
                            Salary = 4100m
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 2,
                            Email = "martin.penev@abv.bg",
                            FirstName = "Martin",
                            JobTitle = "Junior Accountant",
                            LastName = "Penev",
                            Salary = 2500m
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 2,
                            Email = "ivelina.mihailova@gmail.com",
                            FirstName = "Ivelina",
                            JobTitle = "Finance Specialist",
                            LastName = "Mihailova",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 2,
                            Email = "stoyan.georgiev@abv.bg",
                            FirstName = "Stoyan",
                            JobTitle = "Payroll Specialist",
                            LastName = "Georgiev",
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 2,
                            Email = "milko.dimitrov@gmail.com",
                            FirstName = "Milko",
                            JobTitle = "Financial Auditor",
                            LastName = "Dimitrov",
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 2,
                            Email = "tsvetelina.dobreva@abv.bg",
                            FirstName = "Tsvetelina",
                            JobTitle = "Accountant",
                            LastName = "Dobreva",
                            Salary = 2800m
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 2,
                            Email = "plamen.mladenov@gmail.com",
                            FirstName = "Plamen",
                            JobTitle = "Accountant",
                            LastName = "Mladenov",
                            Salary = 3100m
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 2,
                            Email = "gergana.koleva@abv.bg",
                            FirstName = "Gergana",
                            JobTitle = "Financial Analyst",
                            LastName = "Koleva",
                            Salary = 4200m
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 2,
                            Email = "svetoslav.dimitrov@gmail.com",
                            FirstName = "Svetoslav",
                            JobTitle = "Senior Accountant",
                            LastName = "Dimitrov",
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 2,
                            Email = "ivona.pavlova@abv.bg",
                            FirstName = "Ivona",
                            JobTitle = "Financial Specialist",
                            LastName = "Pavlova",
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 2,
                            Email = "stefan.kirilov@gmail.com",
                            FirstName = "Stefan",
                            JobTitle = "Auditor",
                            LastName = "Kirilov",
                            Salary = 3100m
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 3,
                            Email = "svetla.petrova@gmail.com",
                            FirstName = "Svetla",
                            JobTitle = "HR Manager",
                            LastName = "Petrova",
                            Salary = 7200m
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 3,
                            Email = "danail.popov@abv.bg",
                            FirstName = "Danail",
                            JobTitle = "HR Specialist",
                            LastName = "Popov",
                            Salary = 3400m
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 3,
                            Email = "violeta.kirova@gmail.com",
                            FirstName = "Violeta",
                            JobTitle = "Recruitment Specialist",
                            LastName = "Kirova",
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 3,
                            Email = "emil.todorov@abv.bg",
                            FirstName = "Emil",
                            JobTitle = "HR Assistant",
                            LastName = "Todorov",
                            Salary = 2200m
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 3,
                            Email = "monika.stancheva@gmail.com",
                            FirstName = "Monika",
                            JobTitle = "HR Coordinator",
                            LastName = "Stancheva",
                            Salary = 4100m
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 3,
                            Email = "nikolay.lazarov@abv.bg",
                            FirstName = "Nikolay",
                            JobTitle = "Training Specialist",
                            LastName = "Lazarov",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 3,
                            Email = "kristina.pavlova@gmail.com",
                            FirstName = "Kristina",
                            JobTitle = "HR Generalist",
                            LastName = "Pavlova",
                            Salary = 3900m
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 3,
                            Email = "radostin.dinev@abv.bg",
                            FirstName = "Radostin",
                            JobTitle = "HR Specialist",
                            LastName = "Dinev",
                            Salary = 2900m
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 3,
                            Email = "mila.hristova@gmail.com",
                            FirstName = "Mila",
                            JobTitle = "HR Specialist",
                            LastName = "Hristova",
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 3,
                            Email = "diana.zlateva@abv.bg",
                            FirstName = "Diana",
                            JobTitle = "HR Assistant",
                            LastName = "Zlateva",
                            Salary = 2100m
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 4,
                            Email = "rositsa.angelova@gmail.com",
                            FirstName = "Rositsa",
                            JobTitle = "Marketing Manager",
                            LastName = "Angelova",
                            Salary = 8500m
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 4,
                            Email = "simeon.kolev@abv.bg",
                            FirstName = "Simeon",
                            JobTitle = "Marketing Specialist",
                            LastName = "Kolev",
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 4,
                            Email = "lyudmila.mileva@gmail.com",
                            FirstName = "Lyudmila",
                            JobTitle = "Content Writer",
                            LastName = "Mileva",
                            Salary = 2800m
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 4,
                            Email = "tihomir.yordanov@abv.bg",
                            FirstName = "Tihomir",
                            JobTitle = "Graphic Designer",
                            LastName = "Yordanov",
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 4,
                            Email = "gergana.valcheva@gmail.com",
                            FirstName = "Gergana",
                            JobTitle = "SEO Specialist",
                            LastName = "Valcheva",
                            Salary = 3600m
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 4,
                            Email = "bogdan.rusev@abv.bg",
                            FirstName = "Bogdan",
                            JobTitle = "Marketing Analyst",
                            LastName = "Rusev",
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 4,
                            Email = "yana.gospodinova@gmail.com",
                            FirstName = "Yana",
                            JobTitle = "PR Specialist",
                            LastName = "Gospodinova",
                            Salary = 4400m
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 4,
                            Email = "stefan.petkov@abv.bg",
                            FirstName = "Stefan",
                            JobTitle = "Copywriter",
                            LastName = "Petkov",
                            Salary = 2400m
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 4,
                            Email = "lora.borisova@gmail.com",
                            FirstName = "Lora",
                            JobTitle = "Social Media Specialist",
                            LastName = "Borisova",
                            Salary = 3100m
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 4,
                            Email = "viktor.marinov@abv.bg",
                            FirstName = "Viktor",
                            JobTitle = "Marketing Coordinator",
                            LastName = "Marinov",
                            Salary = 3800m
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 4,
                            Email = "petya.mihova@gmail.com",
                            FirstName = "Petya",
                            JobTitle = "Event Specialist",
                            LastName = "Mihova",
                            Salary = 2900m
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 4,
                            Email = "emiliya.hristova@abv.bg",
                            FirstName = "Emiliya",
                            JobTitle = "SEO Analyst",
                            LastName = "Hristova",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 4,
                            Email = "atanas.todorov@gmail.com",
                            FirstName = "Atanas",
                            JobTitle = "Graphic Designer",
                            LastName = "Todorov",
                            Salary = 4100m
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 4,
                            Email = "veronika.ilieva@abv.bg",
                            FirstName = "Veronika",
                            JobTitle = "Content Manager",
                            LastName = "Ilieva",
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 4,
                            Email = "slavi.stoyanov@gmail.com",
                            FirstName = "Slavi",
                            JobTitle = "Copywriter",
                            LastName = "Stoyanov",
                            Salary = 2400m
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 4,
                            Email = "ekaterina.dineva@abv.bg",
                            FirstName = "Ekaterina",
                            JobTitle = "PR Specialist",
                            LastName = "Dineva",
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 5,
                            Email = "aleksandar.zlatev@gmail.com",
                            FirstName = "Aleksandar",
                            JobTitle = "Sales Manager",
                            LastName = "Zlatev",
                            Salary = 9500m
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 5,
                            Email = "sofia.ilieva@abv.bg",
                            FirstName = "Sofia",
                            JobTitle = "Sales Representative",
                            LastName = "Ilieva",
                            Salary = 2600m
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 5,
                            Email = "vladimir.kalchev@gmail.com",
                            FirstName = "Vladimir",
                            JobTitle = "Sales Assistant",
                            LastName = "Kalchev",
                            Salary = 2700m
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 5,
                            Email = "daniela.tsoneva@abv.bg",
                            FirstName = "Daniela",
                            JobTitle = "Account Executive",
                            LastName = "Tsoneva",
                            Salary = 3400m
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 5,
                            Email = "todor.kostov@gmail.com",
                            FirstName = "Todor",
                            JobTitle = "Sales Coordinator",
                            LastName = "Kostov",
                            Salary = 6100m
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 5,
                            Email = "elitsa.gencheva@abv.bg",
                            FirstName = "Elitsa",
                            JobTitle = "Client Consultant",
                            LastName = "Gencheva",
                            Salary = 2100m
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 5,
                            Email = "dimitar.ivanov@gmail.com",
                            FirstName = "Dimitar",
                            JobTitle = "Sales Specialist",
                            LastName = "Ivanov",
                            Salary = 4200m
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 5,
                            Email = "kristina.pavlova@abv.bg",
                            FirstName = "Kristina",
                            JobTitle = "Account Manager",
                            LastName = "Pavlova",
                            Salary = 7400m
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 5,
                            Email = "radostin.stanev@gmail.com",
                            FirstName = "Radostin",
                            JobTitle = "Sales Agent",
                            LastName = "Stanev",
                            Salary = 2900m
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 5,
                            Email = "mila.hristova@abv.bg",
                            FirstName = "Mila",
                            JobTitle = "Sales Admin",
                            LastName = "Hristova",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 5,
                            Email = "zhivko.yordanov@gmail.com",
                            FirstName = "Zhivko",
                            JobTitle = "Sales Engineer",
                            LastName = "Yordanov",
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 5,
                            Email = "ivana.dimitrova@abv.bg",
                            FirstName = "Ivana",
                            JobTitle = "Sales Representative",
                            LastName = "Dimitrova",
                            Salary = 2700m
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 5,
                            Email = "tanya.nikolova@gmail.com",
                            FirstName = "Tanya",
                            JobTitle = "Key Account Manager",
                            LastName = "Nikolova",
                            Salary = 8900m
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 5,
                            Email = "stefan.stoyanov@abv.bg",
                            FirstName = "Stefan",
                            JobTitle = "Field Sales",
                            LastName = "Stoyanov",
                            Salary = 3300m
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 5,
                            Email = "vanya.zheleva@gmail.com",
                            FirstName = "Vanya",
                            JobTitle = "Sales Assistant",
                            LastName = "Zheleva",
                            Salary = 2400m
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 5,
                            Email = "mihaela.kostova@abv.bg",
                            FirstName = "Mihaela",
                            JobTitle = "Sales Intern",
                            LastName = "Kostova",
                            Salary = 2100m
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 5,
                            Email = "boriana.koleva@gmail.com",
                            FirstName = "Boriana",
                            JobTitle = "Business Development Manager",
                            LastName = "Koleva",
                            Salary = 9100m
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 5,
                            Email = "veselin.veselinov@abv.bg",
                            FirstName = "Veselin",
                            JobTitle = "Sales Specialist",
                            LastName = "Veselinov",
                            Salary = 3300m
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 5,
                            Email = "aneliya.petkova@gmail.com",
                            FirstName = "Aneliya",
                            JobTitle = "Sales Executive",
                            LastName = "Petkova",
                            Salary = 3600m
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 5,
                            Email = "plamen.georgiev@abv.bg",
                            FirstName = "Plamen",
                            JobTitle = "Account Specialist",
                            LastName = "Georgiev",
                            Salary = 3400m
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 5,
                            Email = "ralitsa.ivanova@gmail.com",
                            FirstName = "Ralitsa",
                            JobTitle = "Sales Assistant",
                            LastName = "Ivanova",
                            Salary = 2200m
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 5,
                            Email = "nadezhda.marinova@abv.bg",
                            FirstName = "Nadezhda",
                            JobTitle = "Sales Coordinator",
                            LastName = "Marinova",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 5,
                            Email = "viktor.iliev@gmail.com",
                            FirstName = "Viktor",
                            JobTitle = "Sales Trainer",
                            LastName = "Iliev",
                            Salary = 4300m
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 5,
                            Email = "stela.valcheva@abv.bg",
                            FirstName = "Stela",
                            JobTitle = "Client Consultant",
                            LastName = "Valcheva",
                            Salary = 2100m
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 5,
                            Email = "teodor.denev@gmail.com",
                            FirstName = "Teodor",
                            JobTitle = "Sales Engineer",
                            LastName = "Denev",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 5,
                            Email = "silvia.yaneva@abv.bg",
                            FirstName = "Silvia",
                            JobTitle = "Regional Sales Manager",
                            LastName = "Yaneva",
                            Salary = 9700m
                        });
                });

            modelBuilder.Entity("HRAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Admin",
                            Username = "ivan.petrov"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "maria.georgieva"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "georgi.ivanov"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "desislava.nikolova"
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "petar.dimitrov"
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 6,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "anton.simeonov"
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 7,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "radoslav.iliev"
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 8,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "yulian.stoyanov"
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 9,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "valentina.hristova"
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 10,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "milena.yordanova"
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 11,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "nikola.mihailov"
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 12,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "liliya.koleva"
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 13,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "todor.vasilev"
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 14,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "stanislav.petkov"
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 15,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "martin.grozdanov"
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 16,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "ivaylo.marinov"
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 17,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "borislav.pavlov"
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 18,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "vasil.stankov"
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 19,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "polina.dobreva"
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 20,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "kaloyan.angelov"
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 21,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "kristina.filipova"
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 22,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "miroslav.borisov"
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 23,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "teodora.mitkova"
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 24,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "zhivko.yordanov"
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = 25,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "radostin.tsanev"
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = 26,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Admin",
                            Username = "kalina.petkova"
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = 27,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "borislav.todorov"
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = 28,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "ralica.ganeva"
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = 29,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "martin.penev"
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = 30,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "ivelina.mihailova"
                        },
                        new
                        {
                            Id = 31,
                            EmployeeId = 31,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "stoyan.georgiev"
                        },
                        new
                        {
                            Id = 32,
                            EmployeeId = 32,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "milko.dimitrov"
                        },
                        new
                        {
                            Id = 33,
                            EmployeeId = 33,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "tsvetelina.dobreva"
                        },
                        new
                        {
                            Id = 34,
                            EmployeeId = 34,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "plamen.mladenov"
                        },
                        new
                        {
                            Id = 35,
                            EmployeeId = 35,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "gergana.koleva"
                        },
                        new
                        {
                            Id = 36,
                            EmployeeId = 36,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "svetoslav.dimitrov"
                        },
                        new
                        {
                            Id = 37,
                            EmployeeId = 37,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "ivona.pavlova"
                        },
                        new
                        {
                            Id = 38,
                            EmployeeId = 38,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "stefan.kirilov"
                        },
                        new
                        {
                            Id = 39,
                            EmployeeId = 39,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "HR Admin",
                            Username = "svetla.petrova"
                        },
                        new
                        {
                            Id = 40,
                            EmployeeId = 40,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "HR Manager",
                            Username = "danail.popov"
                        },
                        new
                        {
                            Id = 41,
                            EmployeeId = 41,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "HR Manager",
                            Username = "violeta.kirova"
                        },
                        new
                        {
                            Id = 42,
                            EmployeeId = 42,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "emil.todorov"
                        },
                        new
                        {
                            Id = 43,
                            EmployeeId = 43,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "monika.stancheva"
                        },
                        new
                        {
                            Id = 44,
                            EmployeeId = 44,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "nikolay.lazarov"
                        },
                        new
                        {
                            Id = 45,
                            EmployeeId = 45,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "kristina.pavlova"
                        },
                        new
                        {
                            Id = 46,
                            EmployeeId = 46,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "radostin.dinev"
                        },
                        new
                        {
                            Id = 47,
                            EmployeeId = 47,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "mila.hristova"
                        },
                        new
                        {
                            Id = 48,
                            EmployeeId = 48,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "diana.zlateva"
                        },
                        new
                        {
                            Id = 49,
                            EmployeeId = 49,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Admin",
                            Username = "rositsa.angelova"
                        },
                        new
                        {
                            Id = 50,
                            EmployeeId = 50,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "simeon.kolev"
                        },
                        new
                        {
                            Id = 51,
                            EmployeeId = 51,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "lyudmila.mileva"
                        },
                        new
                        {
                            Id = 52,
                            EmployeeId = 52,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "tihomir.yordanov"
                        },
                        new
                        {
                            Id = 53,
                            EmployeeId = 53,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "gergana.valcheva"
                        },
                        new
                        {
                            Id = 54,
                            EmployeeId = 54,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "bogdan.rusev"
                        },
                        new
                        {
                            Id = 55,
                            EmployeeId = 55,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "yana.gospodinova"
                        },
                        new
                        {
                            Id = 56,
                            EmployeeId = 56,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "stefan.petkov"
                        },
                        new
                        {
                            Id = 57,
                            EmployeeId = 57,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "lora.borisova"
                        },
                        new
                        {
                            Id = 58,
                            EmployeeId = 58,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "viktor.marinov"
                        },
                        new
                        {
                            Id = 59,
                            EmployeeId = 59,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "petya.mihova"
                        },
                        new
                        {
                            Id = 60,
                            EmployeeId = 60,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "emiliya.hristova"
                        },
                        new
                        {
                            Id = 61,
                            EmployeeId = 61,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "atanas.todorov"
                        },
                        new
                        {
                            Id = 62,
                            EmployeeId = 62,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "veronika.ilieva"
                        },
                        new
                        {
                            Id = 63,
                            EmployeeId = 63,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "slavi.stoyanov"
                        },
                        new
                        {
                            Id = 64,
                            EmployeeId = 64,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "ekaterina.dineva"
                        },
                        new
                        {
                            Id = 65,
                            EmployeeId = 65,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Admin",
                            Username = "aleksandar.zlatev"
                        },
                        new
                        {
                            Id = 66,
                            EmployeeId = 66,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "sofia.ilieva"
                        },
                        new
                        {
                            Id = 67,
                            EmployeeId = 67,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "vladimir.kalchev"
                        },
                        new
                        {
                            Id = 68,
                            EmployeeId = 68,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "daniela.tsoneva"
                        },
                        new
                        {
                            Id = 69,
                            EmployeeId = 69,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "todor.kostov"
                        },
                        new
                        {
                            Id = 70,
                            EmployeeId = 70,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "elitsa.gencheva"
                        },
                        new
                        {
                            Id = 71,
                            EmployeeId = 71,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "dimitar.ivanov"
                        },
                        new
                        {
                            Id = 72,
                            EmployeeId = 72,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "kristina.pavlova"
                        },
                        new
                        {
                            Id = 73,
                            EmployeeId = 73,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "radostin.stanev"
                        },
                        new
                        {
                            Id = 74,
                            EmployeeId = 74,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "mila.hristova"
                        },
                        new
                        {
                            Id = 75,
                            EmployeeId = 75,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "zhivko.yordanov"
                        },
                        new
                        {
                            Id = 76,
                            EmployeeId = 76,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "ivana.dimitrova"
                        },
                        new
                        {
                            Id = 77,
                            EmployeeId = 77,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "tanya.nikolova"
                        },
                        new
                        {
                            Id = 78,
                            EmployeeId = 78,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "stefan.stoyanov"
                        },
                        new
                        {
                            Id = 79,
                            EmployeeId = 79,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "vanya.zheleva"
                        },
                        new
                        {
                            Id = 80,
                            EmployeeId = 80,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "mihaela.kostova"
                        },
                        new
                        {
                            Id = 81,
                            EmployeeId = 81,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "boriana.koleva"
                        },
                        new
                        {
                            Id = 82,
                            EmployeeId = 82,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "veselin.veselinov"
                        },
                        new
                        {
                            Id = 83,
                            EmployeeId = 83,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "aneliya.petkova"
                        },
                        new
                        {
                            Id = 84,
                            EmployeeId = 84,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "plamen.georgiev"
                        },
                        new
                        {
                            Id = 85,
                            EmployeeId = 85,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "ralitsa.ivanova"
                        },
                        new
                        {
                            Id = 86,
                            EmployeeId = 86,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "nadezhda.marinova"
                        },
                        new
                        {
                            Id = 87,
                            EmployeeId = 87,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "viktor.iliev"
                        },
                        new
                        {
                            Id = 88,
                            EmployeeId = 88,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "stela.valcheva"
                        },
                        new
                        {
                            Id = 89,
                            EmployeeId = 89,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Employee",
                            Username = "teodor.denev"
                        },
                        new
                        {
                            Id = 90,
                            EmployeeId = 90,
                            PasswordHash = "$2a$11$9iOPWHxUBA.46mEztpW/H.2Qteq.CFBhWmXgTfh/I0chD9jSmz5y6",
                            Role = "Manager",
                            Username = "silvia.yaneva"
                        });
                });

            modelBuilder.Entity("HRAPI.Entities.Employee", b =>
                {
                    b.HasOne("HRAPI.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRAPI.Entities.User", b =>
                {
                    b.HasOne("HRAPI.Entities.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("HRAPI.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRAPI.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
